[main]
# Set the primary and fallback fonts (Fontconfig format)
font=FiraCode Nerd Font:size=12,monospace:size=12,Sofia Pro:size=12,Material Design Icons Desktop:size=12,Material Design Icons:size=12,Material Design Iconic Font:size=12
# Customize the input prompt symbol
prompt="  "
# Show application icons next to the names
icon-theme=Adwaita-dark
icons-enabled=yes
# Define the window dimensions
width=30
lines=15
match-counter=yes
placeholder="Search..."
# Specify the target monitor (leave blank to let compositor choose)
# output=DP-1

[colors]
# Formatted as RRGGBBAA (Hexadecimal)
background=1e1f2abb
#text=f8f8f2ff
text=C0CAF5FF
match=8be9fdff
selection=44475aff
#selection-text=f8f8f2ff
selection-text=fbfbf8ff
selection-match=8be9fdff
border=89B4FA55
counter=8c8fa1ff
#prompt=5c5f77ff
prompt=6c6f84dd
placeholder=8c8fa1ff
input=8c8fa1ff

[border]
# Customize the outer edge appearance
width=2
radius=8

[dmenu]
# Behavior when fuzzel is invoked via 'fuzzel --dmenu'
mode=text
exit-immediately-if-empty=no

[key-bindings]
# Custom keyboard control mappings
cancel=Escape Control+g
execute=Return KP_Enter
cursor-left=Left Control+b
cursor-right=Right Control+f
delete-prev=BackSpace

